Change price parsing for side dates
TEA-ebook/im_onix pull request #33
Opened 2016-11-02 15:40 UTC by mfarrica

Le parsing des prix avec plusieurs périodes ne donnait pas le résultat que l'on interprétait via l'ONIX, j'ai donc changé cela pour que les périodes de prix soient celles escomptées.

Exemple :
Avant
```
 Supplies:
  Available in FR starting 2011-08-31
  Prices:
   8.99 EUR tax included until 2016-07-31 <- pb ici
   4.99 EUR tax included from 2016-07-08 until 2016-07-08
   3.99 EUR tax included from 2016-08-01 until 2016-08-15
   8.99 EUR tax included from 2016-07-09 <- pb ici
   8.99 EUR tax included from 2016-08-16
```

Après
```
 Supplies:
  Available in FR starting 2011-08-31
  Prices:
   8.99 EUR tax included until 2016-07-07
   4.99 EUR tax included from 2016-07-08 until 2016-07-08
   8.99 EUR tax included from 2016-07-09 until 2016-07-31
   3.99 EUR tax included from 2016-08-01 until 2016-08-15
   8.99 EUR tax included from 2016-08-16
```

Voici l'ONIX d'exemple qui m'a servi de base de travail [unqualified-prices.xml.zip](https://github.com/TEA-ebook/im_onix/files/567004/unqualified-prices.xml.zip)

See https://tea-ebook.atlassian.net/browse/TR-227

2016-11-02 16:00 UTC, cGuille commented on lib/onix/product.rb
> +      nb_suppliers = supplies.map{|s| s[:suppliers][0].name}.uniq.length
Peut-on ajouter quelques espaces ?

```ruby
nb_suppliers = supplies.map { |supply| supply[:suppliers][0].name }.uniq.length
```

2016-11-02 16:01 UTC, cGuille commented on lib/onix/product.rb
> +      nb_suppliers = supplies.map{|s| s[:suppliers][0].name}.uniq.length
Je ne sais pas trop à quoi ressemble `supplies` mais on n'a pas de risque d'avoir du `nil` quelque part ?

De plus, le `s[:suppliers][0]` laisse penser qu'il peut y avoir plusieurs _suppliers_ par _supply_ ; on ne devrait pas les compter ?

2016-11-02 16:02 UTC, cGuille commented on lib/onix/product.rb
> +      nb_suppliers = supplies.map{|s| s[:suppliers][0].name}.uniq.length
Ah on est dans im_onix, c'est peut-être pas les mêmes conventions…

2016-11-02 16:02 UTC, astranchet commented
Tu peux rajouter des tests en anonymisant le fichier dont tu t'es servi ? À savoir : sur cette gem, la norme est de rajouter un nouveau fichier de test plutôt que d'éditer un existant.

2016-11-02 16:07 UTC, cGuille commented on lib/onix/product.rb
> +      supplies_not_empty = supply.select{ |value| value[:from_date] && value[:until_date] }.sort_by { |hsh| hsh[:from_date] }
Je ne comprends pas comment on peut récupérer **des** _supplies_ en faisant un `select` sur **un** _supply_.

2016-11-02 16:21 UTC, astranchet requested changes

2016-11-02 16:21 UTC, astranchet commented on lib/onix/product.rb
> +    def manage_prices(supply, global_price)
Ça me paraît mauvaise signe que la méthode soit si longue. Je couperais en plusieurs méthodes, et en bonus, le nom de ces méthodes documenterait un peu parce que là, c'est galère de comprendre !

2016-11-02 16:21 UTC, astranchet commented on lib/onix/product.rb
> +      return [global_price] if supplies_not_empty.length == 0 && starts_supplies.length == 0 && ends_supplies.length == 0
Proposition :
```ruby
return [global_price] if [supplies_not_empty, starts_supplies, ends_supplies].all? {|supplies| supplies.empty? }
```

Surtout `empty?` au lieu de `length == 0` mais je trouve que ça permet de plus vite comprendre ou tu veux en venir

2016-11-02 16:21 UTC, astranchet commented on lib/onix/product.rb
> +      if supplies_not_empty.length > 0
`unless supplies_not_empty.empty` ?

2016-11-02 16:21 UTC, astranchet commented on lib/onix/product.rb
> +          if index > 0 && index != supplies_not_empty.length
Si tu le mettais dans un elsif, on pourrait simplifier en mettant seulement `elseif index != supplies_not_empty.length` ?

2016-11-02 16:21 UTC, astranchet commented on lib/onix/product.rb
> +            ns[:until_date] = p[:from_date] - 1
Ça fait quoi une date - 1 ?

2016-11-02 16:21 UTC, astranchet commented on lib/onix/product.rb
> +      elsif starts_supplies.length > 0 && supplies_not_empty.length == 0 && ends_supplies.length == 0
Trop de if imbriqués, je suis perdue, je m'arrête là sur la revue :D 
J'attends des tests et des premiers retours pour mieux comprendre.

2016-11-02 16:24 UTC, astranchet commented on lib/onix/product.rb
> +      nb_suppliers = supplies.map{|s| s[:suppliers][0].name}.uniq.length
(J'ai +1 les 2 commentaires car même fil de réfléxion :D)

2016-11-02 16:26 UTC, cGuille commented on lib/onix/product.rb
> +      return [global_price] if supplies_not_empty.length == 0 && starts_supplies.length == 0 && ends_supplies.length == 0
On peut même aller plus loin, les lignes suivantes sont équivalentes :

```ruby
[].all? {|supplies| supplies.empty? }
[].all? &:empty?
[].all?(&:empty?)

2016-11-02 16:27 UTC, cGuille commented on lib/onix/product.rb
> +      if supplies_not_empty.length > 0
Personnellement, je n'utilise `unless` qu'en fin de ligne, pour des _early return_ ou des trucs comme ça. Je ne l'utilise jamais sous sa forme bloc.

2016-11-07 16:14 UTC, mfarrica commented on lib/onix/product.rb
> +            ns[:until_date] = p[:from_date] - 1
Ça renvoie la date de la veille

2016-11-07 16:17 UTC, mfarrica commented on lib/onix/product.rb
> +          if index > 0 && index != supplies_not_empty.length
non car on ne modifie pas les propriétés du hash et je voulais surtout garder 3 blocs bien distincts avec période début, avant, après celle insérée

2016-11-07 16:20 UTC, mfarrica commented on lib/onix/product.rb
> +    def manage_prices(supply, global_price)
Cette méthode est longue car la règle métier a appliquée est compliquée je vais tenter de découper mais cela ne le rendra pas forcément plus compréhensible/lisible

2016-11-07 16:34 UTC, mfarrica commented
@astranchet j'ai tenté de découper plus ce qui est fait, dis moi si c'est plus compréhensible

2016-11-08 08:40 UTC, astranchet reviewed
C'est un peu plus clair avec ce découpage en méthode mais je pense qu'on peut encore faire mieux :)

2016-11-08 08:40 UTC, astranchet commented on lib/onix/product.rb
> +      supplies_not_empty = supplies.select{ |value| value[:from_date] && value[:until_date] }.sort_by { |hsh| hsh[:from_date] }
Pardon, je vais principalement coder sur du renommage, mais c'est pour mieux comprendre cette portion de code complexe. Est-ce que les 2 boucles pourraient avoir le même nom de variable interne (`supply` au lieu de `value` et `hsh` par exemple ?)

2016-11-08 08:40 UTC, astranchet commented on lib/onix/product.rb
> +      supplies_not_empty = supplies.select{ |value| value[:from_date] && value[:until_date] }.sort_by { |hsh| hsh[:from_date] }
Maintenant que je comprends (un peu) mieux le code, je suis aussi un peu embrouillée par le nom de la variable `supplies_not_empty`. Déjà, il ne ne finit pas par `_supplies` comme ses copains, et je ne suis pas fan de la négation dans le nom. Je propose quelque chose comme `complete_supplies` ou `well_formed_supplies`

2016-11-08 08:40 UTC, astranchet commented on lib/onix/product.rb
> +      if !supplies_not_empty.empty?
Je ne sais pas si ça apporte en lisibilité ou pas, je réfléchis à voix haute, mais puisque `add_between_period_prices` boucle sur le tableau qu'elle reçoit, pourquoi s'embêter à tester s'il est vide ?

2016-11-08 08:40 UTC, astranchet commented on lib/onix/product.rb
> +    def manage_prices(supplies, global_price)
Un petit commentaire du genre "add missing from_date and until_date when they can be guessed" ?

2016-11-08 08:40 UTC, astranchet commented on lib/onix/product.rb
> +      new_suppliers = []
Ta méthode semble vraiment écrite à la php way : créer un nouveau tableau, le remplir, et le retourner. En ruby, on aurait plutôt tendance à le modifier à la volée via un map. Ici ça demanderait un peu de ré-écriture mais je me demande si ça ne faciliterais pas la compréhension.

2016-11-08 08:40 UTC, astranchet commented on lib/onix/product.rb
> +        new_suppliers << p
Parfois on ajoute des `p`

2016-11-08 08:40 UTC, astranchet commented on lib/onix/product.rb
> +          new_suppliers << ns
Parfois on ajoute des `ns` ?

2016-11-08 08:40 UTC, astranchet commented on lib/onix/product.rb
> +      new_suppliers
J'ai toujours pas compris ce que faisait la méthode :D Je croyais avec son nom, et puis à la lecture nope :(

2016-11-08 08:40 UTC, astranchet commented on lib/onix/product.rb
> +      new_suppliers = []
Puisqu'on rajoute des choses au tableau, ça ne serait pas plus clair d'utiliser la méthode qui sert à ça ? (quitte à faire un sort en sortie si besoin)

Est-ce que c'est bien ça qu'on fait au final ?
```ruby
def add_starting_period(supplies, global_price)
    new_supplies = supplies.map do |p|
        ns = global_price.dup
        ns[:from_date] = p[:until_date] + 1
        ns
    end
    supplies.concat(new_supplies)
end
```

ou encore
```ruby
def add_starting_period(supplies, global_price)
    new_supplies = supplies.map do |p|
        global_price.dup.tap |ns|
          ns[:from_date] = p[:until_date] + 1
        end
    end
    supplies.concat(new_supplies)
end
```

2016-11-08 09:49 UTC, mfarrica commented on lib/onix/product.rb
> +      nb_suppliers = supplies.map{|s| s[:suppliers][0].name}.uniq.length
d'après ce que j'ai vu non pas de `nil` et je n'ai pas vu plusieurs suppliers mais je vais voir comment je peux gérer ça

2016-11-10 09:34 UTC, astranchet approved these changes

2016-11-10 09:34 UTC, astranchet commented on lib/onix/product.rb
> +    # add missing from_date and until_date when they can be guessed
Finalement, ça ne serait pas plutôt "add missing periods from global price when necessary" ?

2016-11-10 09:34 UTC, astranchet commented on lib/onix/product.rb
> +      # filter date not nil and sort by this field
Est-ce que ce commentaire est utile encore, vu qu'il est à moitié vrai pour chacune des lignes ?

2016-11-10 10:04 UTC, merged